/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rfw_hotkey_server_commands_MediaKeys */

#ifndef _Included_com_rfw_hotkey_server_commands_MediaKeys
#define _Included_com_rfw_hotkey_server_commands_MediaKeys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rfw_hotkey_server_commands_MediaKeys
 * Method:    volumeMute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rfw_hotkey_1server_commands_MediaKeys_volumeMute
  (JNIEnv *, jclass);

/*
 * Class:     com_rfw_hotkey_server_commands_MediaKeys
 * Method:    volumeDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rfw_hotkey_1server_commands_MediaKeys_volumeDown
  (JNIEnv *, jclass);

/*
 * Class:     com_rfw_hotkey_server_commands_MediaKeys
 * Method:    volumeUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rfw_hotkey_1server_commands_MediaKeys_volumeUp
  (JNIEnv *, jclass);

/*
 * Class:     com_rfw_hotkey_server_commands_MediaKeys
 * Method:    songPrevious
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rfw_hotkey_1server_commands_MediaKeys_songPrevious
  (JNIEnv *, jclass);

/*
 * Class:     com_rfw_hotkey_server_commands_MediaKeys
 * Method:    songNext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rfw_hotkey_1server_commands_MediaKeys_songNext
  (JNIEnv *, jclass);

/*
 * Class:     com_rfw_hotkey_server_commands_MediaKeys
 * Method:    songPlayPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rfw_hotkey_1server_commands_MediaKeys_songPlayPause
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
